language: node_js
node_js:
  - "lts/*"
script:
  - yarn test:unit
  - yarn test:int
  - yarn test:e2e
cache: yarn

language: node_js
node_js:
  - "lts/*"
script: yarn test
after_success: bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: 3985cea5a61f
    - COMMIT_AUTHOR_EMAIL: openapi@bandwidth.com 